# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-10 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190110_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
