# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-10 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190110_1037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meeting_room',
            new_name='MeetingRoom',
        ),
        migrations.RenameModel(
            old_name='Scheduled_record',
            new_name='ReserveRecord',
        ),
    ]
